name: Release

on:
  push:
    tags: # 当我们提交代码为tag 是以'v'开头的时候才会触发自动部署到服务端 如 git push tag v0.1.0
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DIST_ARCHIVE_NAME: vue_starter_dist
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'
      - name: Restore Npm Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install && Build
        working-directory: ./
        run: |
          npm install
          npm run build

      - name: Build Changelog
        id: build_changelog
        if: startsWith(github.ref, 'refs/tags/')
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: ".config/changelog_configuration.json"
          ignorePreReleases: "false"

      - name: Deploy GitHubPage
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: dist

      - name: Archive Dist
        uses: papeloto/action-zip@v1
        with:
          files: dist/
          recursive: false
          dest: ${{ env.DIST_ARCHIVE_NAME }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          files:  |
            ${{ env.DIST_ARCHIVE_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

  ifttt-push:
    runs-on: ubuntu-latest
    needs: [release]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: ifttt Push
        uses: funnyzak/ifttt-webhook-action@v1
        with:
          key: ${{ secrets.IFTTT_KEY }}
          event: push_origin
          value1: 来自GithubAction的消息
          value2: ${{github.repository}} 的Release构建已完成